
import { User, Project, Task } from './types';

/**
 * ENACTUS KISS-KIIT MASTER REGISTRY
 * Source of Truth for RBAC and Onboarding.
 */
export const MOCK_USERS: User[] = [
  // LEADERSHIP & FACULTY (ADMINS)
  {
    id: 'admin-kaish',
    name: 'DR. KAISH Q. KHAN',
    email: 'kaish.khan@kiit.ac.in',
    role: 'ADMIN',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kaish',
    position: 'Faculty In Charge (FIC)',
    isRegistered: true
  },
  {
    id: 'm-pushkar',
    name: 'PUSHKAR ANAND',
    email: '22051872@kiit.ac.in',
    role: 'ADMIN',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pushkar',
    position: 'President',
    isRegistered: true
  },
  { id: 'lead-arnav', name: 'ARNAV CHANDUKA', email: 'arnav.chanduka@gmail.com', role: 'ADMIN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arnav', position: 'Project Lead', isRegistered: false },
  { id: 'lead-ashish', name: 'ASHISH CHOUDHARY', email: 'ashishchaudhary.1111.2004.10.34@gmail.com', role: 'ADMIN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ashish', position: 'Project Lead', isRegistered: false },
  { id: 'lead-palak', name: 'PALAK GOYAL', email: 'goyalpalak708@gmail.com', role: 'ADMIN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Palak', position: 'Project Lead', isRegistered: false },
  { id: 'lead-pritul', name: 'PRITUL CHIRANIA', email: 'pritulchirania@gmail.com', role: 'ADMIN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pritul', position: 'Lead', isRegistered: false },
  { id: 'lead-sriyam', name: 'SRIYAM MOHANTY', email: 'sriyam2004@gmail.com', role: 'ADMIN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sriyam', position: 'Project Lead', isRegistered: false },
  { id: 'lead-samhita', name: 'SAMHITA', email: 'samhita2411@gmail.com', role: 'ADMIN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Samhita', position: 'Project Lead', isRegistered: false },
  { id: 'lead-aryan-p', name: 'ARYAN PANDEY', email: 'aryanhth613@gmail.com', role: 'ADMIN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AryanP', position: 'Project Lead', isRegistered: false },
  { id: 'lead-uttaran', name: 'UTTARAN SARKAR', email: 'sarkaruttaran2004@gmail.com', role: 'ADMIN', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Uttaran', position: 'Project Lead', isRegistered: false },

  // CORE MEMBERS & OPERATIVES (TABLE 1)
  { id: 'u-aadit', name: 'AADIT BAXI', email: 'aaditbaxi111@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aadit', isRegistered: false },
  { id: 'u-aakriti', name: 'AAKRITI ROY', email: 'aakriti1804@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aakriti', isRegistered: false },
  { id: 'u-abir', name: 'ABIR BANERJEE', email: 'abirbanerjee7439@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abir', isRegistered: false },
  { id: 'u-aditi', name: 'ADITI PRABHAT', email: 'aditiprabhat016@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AditiP', isRegistered: false },
  { id: 'u-aditya-j', name: 'ADITYA JAIN', email: 'adi.abhi841@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AdityaJ', isRegistered: false },
  { id: 'u-amitanshu', name: 'AMITANSHU PATTNAIK', email: 'amitanshupattnaik@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amitanshu', isRegistered: false },
  { id: 'u-ananya', name: 'ANANYA SINHA', email: 'ananyasinha376@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ananya', isRegistered: false },
  { id: 'u-anuj', name: 'ANUJ KUMAR', email: 'anujkumar0379456@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anuj', isRegistered: false },
  { id: 'u-any', name: 'ANY DUTTA', email: 'anydutta2308@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Any', isRegistered: false },
  { id: 'u-aryan-g', name: 'ARYAN GUPTA', email: 'aryan45gupta@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AryanG', isRegistered: false },
  { id: 'u-aryan-raj', name: 'ARYAN RAJ SINGH', email: 'aryanraj3142@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AryanR', isRegistered: false },
  { id: 'u-ashirwad', name: 'ASHIRWAD SABAT', email: 'ashirwadsabat@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ashirwad', isRegistered: false },
  { id: 'u-atharv', name: 'ATHARV SINGH', email: 'Communicate.atharv@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Atharv', isRegistered: false },
  { id: 'u-ayushya', name: 'AYUSHYA RAJ', email: 'ayushyaraj8335@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ayushya', isRegistered: false },
  { id: 'u-debasish', name: 'DEBASISH BISOI', email: 'debasishbisoi524@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Debasish', isRegistered: false },
  { id: 'u-devansh', name: 'DEVANSH JOHRI', email: 'devanshjohri18@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Devansh', isRegistered: false },
  { id: 'u-dibyajyoti', name: 'DIBYAJYOTI SETHY', email: 'dibyajyotisethy@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dibyajyoti', isRegistered: false },
  { id: 'u-dipanshu', name: 'DIPANSHU MISHRA', email: 'dipanshumishra880512@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dipanshu', isRegistered: false },
  { id: 'u-harshanshi', name: 'HARSHANSHI SHAH', email: 'harshanshishah@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Harshanshi', isRegistered: false },
  { id: 'u-himanshu', name: 'HIMANSHU LAHARI', email: 'himanshulahri16@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Himanshu', isRegistered: false },
  { id: 'u-khushee', name: 'KHUSHEE MOHAPATRA', email: 'khusheemohapatra91@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Khushee', isRegistered: false },
  { id: 'u-khushi-y', name: 'KHUSHI YADAV', email: 'KHUSHI07YADAV2004@GMAIL.COM', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=KhushiY', isRegistered: false },
  { id: 'u-krishangi', name: 'KRISHANGI DAS', email: 'krishangidas50@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Krishangi', isRegistered: false },
  { id: 'u-krishna', name: 'KRISHNA MURTI', email: 'krishnamurti110014@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=KrishnaM', isRegistered: false },
  { id: 'u-madhusmita', name: 'MADHUSMITA SAHOO', email: 'chandini.mss12@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Madhusmita', isRegistered: false },
  { id: 'u-neeladri', name: 'NEELADRI BANDOPADHYAY', email: 'contact.neeladri@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Neeladri', isRegistered: false },
  { id: 'u-parth', name: 'PARTH MALHOTRA', email: 'malhotraparth2004@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Parth', isRegistered: false },
  { id: 'u-pranav', name: 'PRANAV SHARMA', email: 'pranavsharmabizz@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PranavS', isRegistered: false },
  { id: 'u-preet', name: 'PREET TOMAR', email: 'vipin.tomar2016@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Preet', isRegistered: false },
  { id: 'u-satyajit', name: 'SATYAJIT ROUT', email: 'satyajit2004bbsr@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Satyajit', isRegistered: false },
  { id: 'u-shreya-p', name: 'SHREYA PRAKASH', email: 'shreyaprakash2003@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ShreyaP', isRegistered: false },
  { id: 'u-shreyash', name: 'SHREYASH ROY', email: 'shreyashroy1324@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shreyash', isRegistered: false },
  { id: 'u-shuvam', name: 'SHUVAM PAUL', email: 'shuvam.paul2005@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shuvam', isRegistered: false },
  { id: 'u-sneha', name: 'SNEHA', email: 'snehashrivastava634@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SnehaS', isRegistered: false },
  { id: 'u-trideb', name: 'TRIDEB', email: 'tridebdhar@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Trideb', isRegistered: false },
  { id: 'u-vansh', name: 'VANSH KUMAR', email: 'Vanshkumar1609@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=VanshK', isRegistered: false },
  { id: 'u-vikramaditya', name: 'VIKRAMADITYA SINGH', email: 'vikramadityasingh342@gmail.com', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram', isRegistered: false },

  // UNIVERSITY EMAIL REGISTRY (CODE LIST)
  { id: 'r-amantraa', name: 'Amantraa Roychoudhury', email: '2409003@kiit.ac.in', roll: '2409003', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amantraa', isRegistered: false },
  { id: 'r-aryan-d', name: 'Aryan Dutta Purkayastha', email: '2430088@kiit.ac.in', roll: '2430088', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AryanD', isRegistered: false },
  { id: 'r-faiza', name: 'Faiza Anam', email: '2580113@kims.ac.in', roll: '2580113', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Faiza', isRegistered: false },
  { id: 'r-rishit', name: 'Rishit Kumar Nayak', email: '241551107@kiit.ac.in', roll: '241551107', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rishit', isRegistered: false },
  { id: 'r-nayan', name: 'Nayan Vatsa', email: '2506014@kiit.ac.in', roll: '2506014', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nayan', isRegistered: false },
  { id: 'r-srijoy', name: 'Srijoy Ganguly', email: '25156163@kiit.ac.in', roll: '25156163', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Srijoy', isRegistered: false },
  { id: 'r-tejaswi', name: 'Tejaswi Singh', email: '2401051@kiit.ac.in', roll: '2401051', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tejaswi', isRegistered: false },
  { id: 'r-yash', name: 'Yash Pandey', email: '2401052@kiit.ac.in', roll: '2401052', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=YashP', isRegistered: false },
  { id: 'r-tarun', name: 'Tarun Santosh', email: '24157045@kiit.ac.in', roll: '24157045', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tarun', isRegistered: false },
  { id: 'r-pritha', name: 'Pritha', email: '2305230@kiit.ac.in', roll: '2305230', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pritha', isRegistered: false },
  { id: 'r-arnab', name: 'Arnab Paul', email: '2401006@kiit.ac.in', roll: '2401006', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arnab', isRegistered: false },
  { id: 'r-sumit', name: 'Sumit Dalai', email: '24052512@kiit.ac.in', roll: '24052512', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sumit', isRegistered: false },
  { id: 'r-shloka', name: 'Shloka Sanskruti Mishra', email: '2505971@kiit.ac.in', roll: '2505971', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shloka', isRegistered: false },
  { id: 'r-devyansh', name: 'Devyansh Dhody', email: '2405725@kiit.ac.in', roll: '2405725', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DevyanshD', isRegistered: false },
  { id: 'r-anusha', name: 'Anusha Singh', email: '24051686@kiit.ac.in', roll: '24051686', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anusha', isRegistered: false },
  { id: 'r-krishna-p', name: 'krishna pal', email: '2506011@kiit.ac.in', roll: '2506011', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=KrishnaP', isRegistered: false },
  { id: 'r-kushagra', name: 'Kushagra aryan', email: '25156034@kiit.ac.in', roll: '25156034', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kushagra', isRegistered: false },
  { id: 'r-abhinav', name: 'abhinav kumar dubey', email: '25155108@kiit.ac.in', roll: '25155108', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AbhinavK', isRegistered: false },
  { id: 'r-aditya-k', name: 'aditya kumar', email: '25051062@kiit.ac.in', roll: '25051062', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AdityaK', isRegistered: false },
  { id: 'r-kareena', name: 'Kareena Sahoo', email: '24051937@kiit.ac.in', roll: '24051937', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kareena', isRegistered: false },
  { id: 'r-tishya', name: 'Tishya Jena', email: '24051222@kiit.ac.in', roll: '24051222', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tishya', isRegistered: false },
  { id: 'r-sumang', name: 'SUMANG MISHRA', email: '2405769@kiit.ac.in', roll: '2405769', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sumang', isRegistered: false },
  { id: 'r-sanskriti', name: 'Sanskriti', email: '25051651@kiit.ac.in', roll: '25051651', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sanskriti', isRegistered: false },
  { id: 'r-aditya-s', name: 'Aditya Srivastava', email: '2505758@kiit.ac.in', roll: '2505758', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AdityaSr', isRegistered: false },
  { id: 'r-samriddhi', name: 'Samriddhi yadav', email: '25155865@kiit.ac.in', roll: '25155865', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Samriddhi', isRegistered: false },
  { id: 'r-shubhi', name: 'Shubhi Shandilya', email: '2505169@kiit.ac.in', roll: '2505169', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shubhi', isRegistered: false },
  { id: 'r-srijita', name: 'Srijita Mandal', email: '2405768@kiit.ac.in', roll: '2405768', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Srijita', isRegistered: false },
  { id: 'r-tanmay', name: 'Tanmay Bhardwaj', email: '25159014@kiit.ac.in', roll: '25159014', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tanmay', isRegistered: false },
  { id: 'r-ritaja', name: 'Ritaja Mishra', email: '25156108@kiit.ac.in', roll: '25156108', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ritaja', isRegistered: false },
  { id: 'r-janvi', name: 'JANVI AGARWAL', email: '2546028@ksec.kiit.ac.in', roll: '2546028', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Janvi', isRegistered: false },
  { id: 'r-garima', name: 'Garima Kumari', email: '24052450@kiit.ac.in', roll: '24052450', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Garima', isRegistered: false },
  { id: 'r-tamanna', name: 'Tamanna Paul', email: '2430280@kiit.ac.in', roll: '2430280', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tamanna', isRegistered: false },
  { id: 'r-anwesha', name: 'anwesha dutta', email: '2401005@kiit.ac.in', roll: '2401005', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AnweshaD', isRegistered: false },
  { id: 'r-premangshu', name: 'premangshu', email: '2430177@kiit.ac.in', roll: '2430177', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Premangshu', isRegistered: false },
  { id: 'r-rajmani', name: 'rajmani', email: '24052241@kiit.ac.in', roll: '24052241', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajmani', isRegistered: false },
  { id: 'r-shalin', name: 'shalin mani', email: '25155390@kiit.ac.in', roll: '25155390', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shalin', isRegistered: false },
  { id: 'r-aryan-sh', name: 'Aryan Sharma', email: '22051063@kiit.ac.in', roll: '22051063', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AryanS', isRegistered: false },
  { id: 'r-soumyajit', name: 'Soumyajit Ghosh', email: '23051387@kiit.ac.in', roll: '23051387', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Soumyajit', isRegistered: false },
  { id: 'r-diksha', name: 'Diksha Dwivedi', email: '25051820@kiit.ac.in', roll: '25051820', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diksha', isRegistered: false },
  { id: 'r-yashwanth', name: 'K Sri Yashwanth', email: '25206030@ksrm.ac.in', roll: '25206030', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yashwanth', isRegistered: false },
  { id: 'r-versha', name: 'Kumari Versha rani', email: '25206035@ksrm.ac.in', roll: '25206035', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Versha', isRegistered: false },
  { id: 'r-arpit', name: 'Arpit', email: '2505016@kiit.ac.in', roll: '2505016', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arpit', isRegistered: false },
  { id: 'r-nitika', name: 'Nitika Jha', email: '25155619@kiit.ac.in', roll: '25155619', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nitika', isRegistered: false },
  { id: 'r-aditya-ch', name: 'Aditya Chowdhury', email: '25155004@kiit.ac.in', roll: '25155004', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AdityaCh', isRegistered: false },
  { id: 'r-ayush-p', name: 'Ayush Pradhan', email: '2505940@kiit.ac.in', roll: '2505940', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AyushP', isRegistered: false },
  { id: 'r-kesav', name: 'Kesav dhanuka', email: '25155609@kiit.ac.in', roll: '25155609', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kesav', isRegistered: false },
  { id: 'r-anshuman', name: 'Anshuman sharma', email: '25155242@kiit.ac.in', roll: '25155242', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anshuman', isRegistered: false },
  { id: 'r-priyam', name: 'Priyam Utkarsh', email: '25051374@kiit.ac.in', roll: '25051374', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priyam', isRegistered: false },
  { id: 'r-shaily', name: 'Shaily Jalan', email: '25155983@kiit.ac.in', roll: '25155983', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shaily', isRegistered: false },
  { id: 'r-aarna', name: 'Aarna', email: '2505518@kiit.ac.in', roll: '2505518', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aarna', isRegistered: false },
  { id: 'r-prabhjot', name: 'Prabhjot Singh', email: '25051639@kiit.ac.in', roll: '25051639', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Prabhjot', isRegistered: false },
  { id: 'r-ananya-sh', name: 'Ananya Shankar', email: '2505007@kiit.ac.in', roll: '2505007', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AnanyaSh', isRegistered: false },
  { id: 'r-krishna-ag', name: 'Krishna Agarwal', email: '2406035@kiit.ac.in', roll: '2406035', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=KrishnaAg', isRegistered: false },
  { id: 'r-ayan', name: 'Ayan Biswas', email: '24155620@kiit.ac.in', roll: '24155620', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ayan', isRegistered: false },
  { id: 'r-prabhajeet', name: 'Prabhajeet das', email: '24155340@kiit.ac.in', roll: '24155340', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Prabhajeet', isRegistered: false },
  { id: 'r-arpan', name: 'Arpan Kumar', email: '2406014@kiit.ac.in', roll: '2406014', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arpan', isRegistered: false },
  { id: 'r-priyanshu', name: 'Priyanshu Das', email: '2402039@kiit.ac.in', roll: '2402039', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priyanshu', isRegistered: false },
  { id: 'r-taha', name: 'TAHA MERCHANT', email: '2426017@kiit.ac.in', roll: '2426017', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Taha', isRegistered: false },
  { id: 'r-abhay', name: 'Abhay singh', email: '2406002@kiit.ac.in', roll: '2406002', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abhay', isRegistered: false },
  { id: 'r-aanshika', name: 'AANSHIKA SINGH', email: '24158002@kiit.ac.in', roll: '24158002', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aanshika', isRegistered: false },
  { id: 'r-krishanu', name: 'Krishanu Kundu', email: '24158014@kiit.ac.in', roll: '24158014', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Krishanu', isRegistered: false },
  { id: 'r-jagrati', name: 'Jagrati Sharma', email: '2405281@kiit.ac.in', roll: '2405281', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jagrati', isRegistered: false },
  { id: 'r-suraj', name: 'Suraj Nayak', email: '24051818@kiit.ac.in', roll: '24051818', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suraj', isRegistered: false },
  { id: 'r-bristi', name: 'Bristi Bera', email: '24051546@kiit.ac.in', roll: '24051546', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bristi', isRegistered: false },
  { id: 'r-shaswat', name: 'Shaswat Prasad', email: '24051511@kiit.ac.in', roll: '24051511', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shaswat', isRegistered: false },
  { id: 'r-sampoorna', name: 'Sampoorna Ghosh', email: '24052174@kiit.ac.in', roll: '24052174', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sampoorna', isRegistered: false },
  { id: 'r-dipanjan', name: 'Dipanjan Chakraborty', email: '2405428@kiit.ac.in', roll: '2405428', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dipanjan', isRegistered: false },
  { id: 'r-krishnendu', name: 'Krishnendu Karmakar', email: '2406036@kiit.ac.in', roll: '2406036', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Krishnendu', isRegistered: false },
  { id: 'r-manao', name: 'Lukram Manao', email: '2432013@ksmc.kiit.ac.in', roll: '2432013', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Manao', isRegistered: false },
  { id: 'r-atreyi', name: 'Atreyi Dasgupta', email: '2405419@kiit.ac.in', roll: '2405419', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Atreyi', isRegistered: false },
  { id: 'r-diya', name: 'Diya', email: '2405432@kiit.ac.in', roll: '2405432', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Diya', isRegistered: false },
  { id: 'r-shourya', name: 'Shourya Kumar', email: '24051738@kiit.ac.in', roll: '24051738', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shourya', isRegistered: false },
  { id: 'r-sneha-b', name: 'SNEHA BISWAS', email: '24051057@kiit.ac.in', roll: '24051057', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SnehaB', isRegistered: false },
  { id: 'r-ananya-y', name: 'Ananya Yadav', email: '24158039@kiit.ac.in', roll: '24158039', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AnanyaY', isRegistered: false },
  { id: 'r-unnita', name: 'Unnita pal', email: '2430276@kiit.ac.in', roll: '2430276', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Unnita', isRegistered: false },
  { id: 'r-arijit', name: 'Arijit Saha', email: '24051471@kiit.ac.in', roll: '24051471', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arijit', isRegistered: false },
  { id: 'r-soham-sh', name: 'Soham shyamal', email: '24155962@kiit.ac.in', roll: '24155962', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SohamSh', isRegistered: false },
  { id: 'r-girika', name: 'GIRIKA SARKAR', email: '25052099@kiit.ac.in', roll: '25052099', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Girika', isRegistered: false },
  { id: 'r-shambhawi', name: 'Shambhawi', email: '24051509@kiit.ac.in', roll: '24051509', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shambhawi', isRegistered: false },
  { id: 'r-shivam', name: 'Shivam Mishra', email: '24051513@kiit.ac.in', roll: '24051513', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shivam', isRegistered: false },
  { id: 'r-mayank', name: 'Mayank Kumar', email: '2301023@kiit.ac.in', roll: '2301023', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mayank', isRegistered: false },
  { id: 'r-sayantan', name: 'Sayantan Sarkar', email: '24051576@kiit.ac.in', roll: '24051576', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sayantan', isRegistered: false },
  { id: 'r-mayank-kr', name: 'Mayank Krishna', email: '2505431@kiit.ac.in', roll: '2505431', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MayankKr', isRegistered: false },
  { id: 'r-rakshika', name: 'Rakshika Tiwari', email: '25051782@kiit.ac.in', roll: '25051782', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rakshika', isRegistered: false },
  { id: 'r-abhinibesh', name: 'ABHINIBESH GHOSH', email: '2505246@kiit.ac.in', roll: '2505246', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abhinibesh', isRegistered: false },
  { id: 'r-raj', name: 'Raj Jha', email: '2406046@kiit.ac.in', roll: '2406046', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RajJ', isRegistered: false },
  { id: 'r-suchit', name: 'Suchit das', email: '23053311@kiit.ac.in', roll: '23053311', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suchit', isRegistered: false },
  { id: 'r-sampreet', name: 'Sampreet Sarkar', email: '23051945@kiit.ac.in', roll: '23051945', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sampreet', isRegistered: false },
  { id: 'r-shaurya-a', name: 'Shaurya Amit', email: '2330448@kiit.ac.in', roll: '2330448', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ShauryaA', isRegistered: false },
  { id: 'r-satya', name: 'Satya Sundar Sahu', email: '24052252@kiit.ac.in', roll: '24052252', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Satya', isRegistered: false },
  { id: 'r-girijatmak', name: 'Girijatmak Behera', email: '2376085@ksom.ac.in', roll: '2376085', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Girijatmak', isRegistered: false },
  { id: 'r-aadya', name: 'Aadya Jaisawal', email: '25159006@kiit.ac.in', roll: '25159006', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aadya', isRegistered: false },
  { id: 'r-mahi', name: 'Mahi Mishra', email: '25051832@kiit.ac.in', roll: '25051832', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mahi', isRegistered: false },
  { id: 'r-shourya-p', name: 'Shourya Sambhavya Pandey', email: '2506026@kiit.ac.in', roll: '2506026', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ShouryaP', isRegistered: false },
  { id: 'r-subham-m', name: 'Subham Maiti', email: '2505233@kiit.ac.in', roll: '2505233', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SubhamM', isRegistered: false },
  { id: 'r-surakshya', name: 'SURAKSHYA LENKA', email: '2570292@kiit.ac.in', roll: '2570292', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Surakshya', isRegistered: false },
  { id: 'r-aly', name: 'Aly Barry', email: '25201070@ksrm.ac.in', roll: '25201070', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aly', isRegistered: false },
  { id: 'r-subham-s', name: 'Subham Kumar Sahoo', email: '25201069@ksrm.ac.in', roll: '25201069', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SubhamS', isRegistered: false },
  { id: 'r-bithal', name: 'BITHAL PADHIARY', email: '251551013@kiit.ac.in', roll: '251551013', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bithal', isRegistered: false },
  { id: 'r-shreya-sh', name: 'shreya sharma', email: '2505974@kiit.ac.in', roll: '2505974', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ShreyaSh', isRegistered: false },
  { id: 'r-swattak', name: 'Swattak Pramanik', email: '25051734@kiit.ac.in', roll: '25051734', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Swattak', isRegistered: false },
  { id: 'r-shuvam-s', name: 'shuvam sahoo', email: '25156053@kiit.ac.in', roll: '25156053', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ShuvamS', isRegistered: false },
  { id: 'r-snigdha', name: 'Snigdha Singh', email: '25051865@kiit.ac.in', roll: '25051865', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Snigdha', isRegistered: false },
  { id: 'r-aditya-kr', name: 'Aditya Kumar', email: '25155468@kiit.ac.in', roll: '25155468', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AdityaKr', isRegistered: false },
  { id: 'r-debangana', name: 'Debangana Chakraborty', email: '25161022@kiit.ac.in', roll: '25161022', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Debangana', isRegistered: false },
  { id: 'r-bhavesh', name: 'Bhavesh Kumar Tiwari', email: '2505725@kiit.ac.in', roll: '2505725', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bhavesh', isRegistered: false },
  { id: 'r-swayansh', name: 'Swayansh Mohapatra', email: '25156118@kiit.ac.in', roll: '25156118', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Swayansh', isRegistered: false },
  { id: 'r-akshita', name: 'Akshita Rai', email: '25157045@kiit.ac.in', roll: '25157045', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Akshita', isRegistered: false },
  { id: 'r-kaushiki', name: 'Kaushiki', email: '2505682@kiit.ac.in', roll: '2505682', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kaushiki', isRegistered: false },
  { id: 'r-pranika', name: 'Pranika Sinha', email: '2505439@kiit.ac.in', roll: '2505439', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pranika', isRegistered: false },
  { id: 'r-sanskriti-v', name: 'Sanskriti', email: '2405147@kiit.ac.in', roll: '2405147', role: 'MEMBER', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SanskritiV', isRegistered: false },
];

export const MOCK_PROJECTS: Project[] = [];
export const MOCK_TASKS: Task[] = [];
